name: Dockerizing the Flask app and pushing to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Update GitHub Actions runner
      - name: Update GitHub runner
        run: sudo apt-get update -y && sudo apt-get upgrade -y

      # Login to Docker Hub using authentication token
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image and push
      - name: Build Docker image and push
        run: docker buildx create --use && docker buildx build --platform linux/arm64,linux/amd64 --push -t cyberprince/flaskverapp:v1 .