name: Dockerizing Flask app / pushing to DockerHub / running Terraform to AKS

on:
  push:
    branches:
      - main

# First job is to dockerize the app and push to Docker Hub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Update GitHub Actions runner
      #- name: Update GitHub runner
      #  run: sudo apt-get update -y && sudo apt-get upgrade -y

      # Login to Docker Hub using authentication token
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ vars.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image and push
      #- name: Build Docker image and push
      #  run: docker buildx create --use && docker buildx build --platform linux/arm64,linux/amd64 --push -t cyberprince/flaskverapp:v1 .


# Deploying DockerHub image to run on Azure Kubernetes Service

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Update GitHub runner
      #  run: sudo apt-get update -y && sudo apt-get upgrade -y

      # Using wrapper as per Terraform Team's issue thread suggestion
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false


      - name: Start Terraform
        run: |
          terraform init
          terraform validate
          terraform fmt

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}