name: Dockerizing Flask app / pushing to DockerHub / running Terraform to AKS

on:
  push:
    branches:
      - main

# First job is to dockerize the app and push to Docker Hub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Update GitHub Actions runner
      - name: Update GitHub runner
        run: sudo apt-get update -y && sudo apt-get upgrade -y

      # Login to Docker Hub using authentication token
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ vars.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image and push
      - name: Build Docker image and push
        run: docker buildx create --use && docker buildx build --platform linux/arm64,linux/amd64 --push -t cyberprince/flaskverapp:v1 .


# Deploying DockerHub image to run on Azure Kubernetes Service

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update GitHub runner
        run: sudo apt-get update -y && sudo apt-get upgrade -y

      - name: Set Terraform input variables
        run: |
          echo "##[set-output name=client_id;]${{ secrets.CLIENT_ID }}"
          echo "##[set-output name=client_secret;]${{ secrets.CLIENT_SECRET }}"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Start Terraform
        run: |
          terraform init
          terraform validate
          terraform fmt

      - name: Create infrastructure
        run: terraform apply -auto-approve